//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HnrMgmtAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AwdRecord
    {
        public string AwdRecID { get; set; }
        public string AwdID { get; set; }
        public string Year { get; set; }
        public string Term { get; set; }
        public string IsTeam { get; set; }
        public string ProName { get; set; }
        public string AwdeeID { get; set; }
        public string OrgID { get; set; }
        public string Teacher { get; set; }
        public string PicUrl { get; set; }
    }
}
