//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HnrMgmtAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HnrRecord
    {
        public string HnrRecID { get; set; }
        public string HonorID { get; set; }
        public string Annual { get; set; }
        public string Time { get; set; }
        public string AwdeeID { get; set; }
        public string OrgID { get; set; }
        public string Branch { get; set; }
        public string FileUrl { get; set; }
    }
}
