//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HnrMgmtAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AwdRecord_Rec
    {
        public string AwdRecID { get; set; }
        public string AwdID { get; set; }
        public string AwdName { get; set; }
        public string AwdGradeName { get; set; }
        public string AwdGrade { get; set; }
        public string Year { get; set; }
        public string Time { get; set; }
        public string Term { get; set; }
        public string IsTeam { get; set; }
        public string ProName { get; set; }
        public string Teacher { get; set; }
        public string OrgID { get; set; }
        public string OrgName { get; set; }
        public string TeamID { get; set; }
        public string TeamAwdeeID { get; set; }
        public string TeamAwdeeName { get; set; }
        public string TeamAwdeeOrgID { get; set; }
        public string TeamAwdeeOrgName { get; set; }
        public string TeamAwdeeBranch { get; set; }
        public System.DateTime ApplyTime { get; set; }
        public string ApplyAccountID { get; set; }
        public string ApplyAccountName { get; set; }
        public string ApplyAccountOrgID { get; set; }
        public string ApplyAccountOrgName { get; set; }
        public string ApplyAccountRoleID { get; set; }
        public string ApplyAccountRoleName { get; set; }
        public string Reason { get; set; }
        public string FileUrl { get; set; }
        public string State { get; set; }
    }
}
