//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HnrMgmtAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_HnrRecord
    {
        public string HnrRecID { get; set; }
        public string AwardeeID { get; set; }
        public string AwardeeName { get; set; }
        public string AwardeeOrgID { get; set; }
        public string AwardeeOrgName { get; set; }
        public string AwardeeBranch { get; set; }
        public string HnrName { get; set; }
        public string HnrGradeName { get; set; }
        public string HnrAnnual { get; set; }
        public string HnrTime { get; set; }
        public string ApplyAccountID { get; set; }
        public string ApplyAccountName { get; set; }
        public string ApplyAccountOrgID { get; set; }
        public string ApplyAccountOrgName { get; set; }
        public string ApplyAccountRoleID { get; set; }
        public string ApplyAccountRoleName { get; set; }
        public System.DateTime ApplyTime { get; set; }
        public string Reason { get; set; }
        public string FileUrl { get; set; }
        public string State { get; set; }
    }
}
