//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HnrMgmtAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TeamAwdRecord
    {
        public string Name { get; set; }
        public string GradeName { get; set; }
        public string Grade { get; set; }
        public string Year { get; set; }
        public string Term { get; set; }
        public string IsTeam { get; set; }
        public string ProName { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Rank { get; set; }
        public string Branch { get; set; }
        public string Teacher { get; set; }
        public string PicUrl { get; set; }
    }
}
