//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HnrMgmtAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Account
    {
        public string AccountID { get; set; }
        public string AccountName { get; set; }
        public string OrgID { get; set; }
        public string OrgName { get; set; }
        public string RoleID { get; set; }
        public string RoleName { get; set; }
        public string Tel { get; set; }
        public string State { get; set; }
    }
}
