//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HnrMgmtAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AwdRecord
    {
        public int ID { get; set; }
        public string AwdRecID { get; set; }
        public string AwardeeID { get; set; }
        public string AwardeeName { get; set; }
        public string AwardeeOrgID { get; set; }
        public string AwardeeOrgName { get; set; }
        public string AwardeeBranch { get; set; }
        public string AwardeeRank { get; set; }
        public string AwdName { get; set; }
        public string AwdOrgID { get; set; }
        public string AwdOrgName { get; set; }
        public string AwdProName { get; set; }
        public string AwdGrade { get; set; }
        public string AwdGradeName { get; set; }
        public string AwdYear { get; set; }
        public string AwdTerm { get; set; }
        public string AwdTime { get; set; }
        public string IsTeam { get; set; }
        public string Teacher { get; set; }
        public string ApplyAccountID { get; set; }
        public string ApplyAccountName { get; set; }
        public string ApplyAccountOrgID { get; set; }
        public string ApplyAccountOrgName { get; set; }
        public string AppltAccountRoleID { get; set; }
        public string AppltAccountRoleName { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public string Reason { get; set; }
        public string FileUrl { get; set; }
        public string State { get; set; }
    }
}
