//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HnrMgmtAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SearchIndex
    {
        public string RecordID { get; set; }
        public string IsHnrRec { get; set; }
        public string Time { get; set; }
        public string HnrAwdID { get; set; }
        public string OrgID { get; set; }
        public string Year { get; set; }
        public string Term { get; set; }
        public string ProName { get; set; }
        public string Teacher { get; set; }
        public string Branch { get; set; }
        public System.DateTime ApplyTime { get; set; }
    }
}
