//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HnrMgmtAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TeamMembers
    {
        public int ID { get; set; }
        public string TeamID { get; set; }
        public string AwdeeID { get; set; }
        public string AwdeeName { get; set; }
        public string AwdeeOrgID { get; set; }
        public string AwdeeOrgName { get; set; }
        public string AwdeeBranch { get; set; }
        public string AwdeeRank { get; set; }
    }
}
